using UnityEngine;

namespace AnimalGame.RobotMap
{
    public sealed class RobotCameraFollow : MonoBehaviour
    {
        [Header("Position Follow")]
        [SerializeField, Min(0f)] private float positionDamping = 0.18f;

        [Header("Rotation Follow")]
        [SerializeField, Min(0f)] private float rotationDamping = 0.22f;

        [Tooltip("Keeps the robot's forward direction at the top of the screen.")]
        [SerializeField] private bool followTargetRotation = true;

        [Header("Manual Imbalance Preview")]
        [Tooltip("Enables number-key camera imbalance presets. This is visual only and does not read or modify terrain traversal.")]
        [SerializeField] private bool enableManualImbalancePreview = true;

        [Tooltip("Target imbalance used by keys 1 and 4.")]
        [SerializeField, Range(0f, 1f)] private float lightImbalance = 0.3f;

        [Tooltip("Target imbalance used by keys 2 and 5.")]
        [SerializeField, Range(0f, 1f)] private float mediumImbalance = 0.62f;

        [Tooltip("Target imbalance used by keys 3 and 6.")]
        [SerializeField, Range(0f, 1f)] private float severeImbalance = 1f;

        [Tooltip("Maximum screen roll at severe imbalance. The fixed screen-space UI does not rotate.")]
        [SerializeField, Range(0f, 30f)] private float maximumRollAngle = 14f;

        [Tooltip("Maximum off-axis yaw at severe imbalance. This makes the orthographic camera observe the 2D map from the side instead of remaining perfectly perpendicular.")]
        [SerializeField, Range(0f, 40f)] private float maximumYawAngle = 20f;

        [Tooltip("Maximum camera-centre displacement in world units at severe imbalance.")]
        [SerializeField, Min(0f)] private float maximumLateralOffset = 1.05f;

        [Tooltip("Natural frequency of the imbalance spring. Lower values take longer to reach the selected preset.")]
        [SerializeField, Range(0.1f, 5f)] private float imbalanceSpringFrequency = 0.85f;

        [Tooltip("Damping ratio of the imbalance spring. Values below 1 allow a small natural overshoot before settling.")]
        [SerializeField, Range(0.1f, 1.5f)] private float imbalanceDampingRatio = 0.58f;

        [Tooltip("Very small smooth angular variation while imbalanced. This avoids a perfectly static mechanical pose without creating frame-to-frame jitter.")]
        [SerializeField, Range(0f, 4f)] private float imbalanceNoiseAngle = 0.65f;

        [Tooltip("Frequency in Hz of the smooth imbalance variation.")]
        [SerializeField, Range(0.05f, 3f)] private float imbalanceNoiseFrequency = 0.42f;

        [Header("Near-Tip Wobble Preview")]
        [Tooltip("Imbalance magnitude at which the unstable rocking layer begins to appear.")]
        [SerializeField, Range(0f, 0.95f)] private float wobbleStartImbalance = 0.22f;

        [Tooltip("Base frequency in Hz of the large irregular rocking motion.")]
        [SerializeField, Range(0.1f, 4f)] private float wobbleFrequency = 1.05f;

        [Tooltip("Maximum additional Roll generated by unstable rocking at severe imbalance.")]
        [SerializeField, Range(0f, 15f)] private float maximumWobbleRollAngle = 4.5f;

        [Tooltip("Maximum additional off-axis Yaw generated by unstable rocking at severe imbalance.")]
        [SerializeField, Range(0f, 15f)] private float maximumWobbleYawAngle = 3.2f;

        [Tooltip("Maximum additional lateral camera movement generated by unstable rocking.")]
        [SerializeField, Min(0f)] private float maximumWobbleOffset = 0.24f;

        [Tooltip("Frequency in Hz of the small high-frequency shake near loss of balance.")]
        [SerializeField, Range(1f, 15f)] private float tremorFrequency = 5.8f;

        [Tooltip("Maximum angular shake layered over the large rocking motion.")]
        [SerializeField, Range(0f, 5f)] private float maximumTremorAngle = 1.1f;

        [Tooltip("Maximum lateral high-frequency shake layered over the large rocking motion.")]
        [SerializeField, Min(0f)] private float maximumTremorOffset = 0.065f;

        [Tooltip("Extra outward Roll pulse that periodically pulls the camera closer to tipping in the currently selected imbalance direction.")]
        [SerializeField, Range(0f, 10f)] private float outwardLurchAngle = 2.6f;

        public Transform Target { get; set; }
        public float CurrentPreviewImbalance => currentImbalance;
        public float TargetPreviewImbalance => targetImbalance;

        private Vector3 followPoint;
        private Vector3 followVelocity;
        private float followAngle;
        private float followAngularVelocity;
        private float cameraDistance = 10f;
        private float targetImbalance;
        private float currentImbalance;
        private float imbalanceVelocity;
        private float imbalanceNoiseSeed;
        private bool followPoseInitialized;

        private void Awake()
        {
            imbalanceNoiseSeed = Mathf.Abs(GetInstanceID() * 0.0137f) + 17.3f;
        }

        public void SnapToTarget()
        {
            if (Target == null)
                return;

            cameraDistance = Mathf.Max(
                0.1f,
                Mathf.Abs(transform.position.z - Target.position.z));
            followPoint = Target.position;
            followAngle = followTargetRotation
                ? Target.eulerAngles.z
                : transform.eulerAngles.z;
            followVelocity = Vector3.zero;
            followAngularVelocity = 0f;
            followPoseInitialized = true;
            ApplyCameraPose();
        }

        private void LateUpdate()
        {
            if (Target == null)
                return;

            if (!followPoseInitialized)
                SnapToTarget();

            ReadManualImbalanceKeys();
            UpdateImbalanceSpring();

            followPoint = Vector3.SmoothDamp(
                followPoint,
                Target.position,
                ref followVelocity,
                Mathf.Max(0.0001f, positionDamping));

            if (followTargetRotation)
            {
                followAngle = Mathf.SmoothDampAngle(
                    followAngle,
                    Target.eulerAngles.z,
                    ref followAngularVelocity,
                    Mathf.Max(0.0001f, rotationDamping));
            }

            ApplyCameraPose();
        }

        private void ReadManualImbalanceKeys()
        {
            if (!enableManualImbalancePreview)
            {
                targetImbalance = 0f;
                return;
            }

            if (PreviewKeyDown(KeyCode.Alpha1, KeyCode.Keypad1))
                targetImbalance = -lightImbalance;
            else if (PreviewKeyDown(KeyCode.Alpha2, KeyCode.Keypad2))
                targetImbalance = -mediumImbalance;
            else if (PreviewKeyDown(KeyCode.Alpha3, KeyCode.Keypad3))
                targetImbalance = -severeImbalance;
            else if (PreviewKeyDown(KeyCode.Alpha4, KeyCode.Keypad4))
                targetImbalance = lightImbalance;
            else if (PreviewKeyDown(KeyCode.Alpha5, KeyCode.Keypad5))
                targetImbalance = mediumImbalance;
            else if (PreviewKeyDown(KeyCode.Alpha6, KeyCode.Keypad6))
                targetImbalance = severeImbalance;
            else if (PreviewKeyDown(KeyCode.Alpha0, KeyCode.Keypad0))
                targetImbalance = 0f;
        }

        private void UpdateImbalanceSpring()
        {
            float deltaTime = Mathf.Min(Time.deltaTime, 0.05f);
            if (deltaTime <= 0f)
                return;

            float angularFrequency = 2f
                                     * Mathf.PI
                                     * Mathf.Max(0.1f, imbalanceSpringFrequency);
            float springAcceleration = angularFrequency
                                       * angularFrequency
                                       * (targetImbalance - currentImbalance);
            float dampingAcceleration = 2f
                                        * Mathf.Max(0.1f, imbalanceDampingRatio)
                                        * angularFrequency
                                        * imbalanceVelocity;
            imbalanceVelocity += (springAcceleration - dampingAcceleration)
                                 * deltaTime;
            currentImbalance += imbalanceVelocity * deltaTime;

            if (Mathf.Abs(currentImbalance) > 1.25f)
            {
                currentImbalance = Mathf.Clamp(currentImbalance, -1.25f, 1.25f);
                imbalanceVelocity *= 0.35f;
            }
        }

        private void ApplyCameraPose()
        {
            float imbalanceMagnitude = Mathf.Clamp01(Mathf.Abs(currentImbalance));
            float smoothNoise = (Mathf.PerlinNoise(
                                     imbalanceNoiseSeed,
                                     Time.time * imbalanceNoiseFrequency)
                                 * 2f
                                 - 1f)
                                * imbalanceNoiseAngle
                                * imbalanceMagnitude;
            float wobbleStrength = Mathf.SmoothStep(
                0f,
                1f,
                Mathf.InverseLerp(
                    wobbleStartImbalance,
                    1f,
                    imbalanceMagnitude));
            float wobblePhase = Time.time
                                * Mathf.PI
                                * 2f
                                * wobbleFrequency;
            float phaseWarp = (Mathf.PerlinNoise(
                                   imbalanceNoiseSeed + 31.7f,
                                   Time.time * 0.29f)
                               * 2f
                               - 1f)
                              * 1.15f;
            float primaryWobble = Mathf.Sin(wobblePhase + phaseWarp);
            float secondaryWobble = Mathf.Sin(
                wobblePhase * 1.73f + imbalanceNoiseSeed) * 0.34f;
            float irregularWobble = Mathf.Clamp(
                                        (primaryWobble + secondaryWobble) / 1.34f,
                                        -1f,
                                        1f)
                                    * wobbleStrength;
            float tremor = (Mathf.PerlinNoise(
                                imbalanceNoiseSeed + 73.1f,
                                Time.time * tremorFrequency)
                            * 2f
                            - 1f)
                           * wobbleStrength;
            float imbalanceSign = Mathf.Abs(currentImbalance) > 0.001f
                ? Mathf.Sign(currentImbalance)
                : Mathf.Sign(targetImbalance);
            float outwardPulseSource = Mathf.Sin(
                wobblePhase * 0.47f + imbalanceNoiseSeed * 0.31f);
            float outwardPulse = Mathf.Pow(
                                     Mathf.Clamp01(
                                         (outwardPulseSource + 1f) * 0.5f),
                                     4f)
                                 * imbalanceSign
                                 * wobbleStrength;

            float rollAngle = currentImbalance * maximumRollAngle
                              + smoothNoise
                              + irregularWobble * maximumWobbleRollAngle
                              + tremor * maximumTremorAngle
                              + outwardPulse * outwardLurchAngle;
            float yawAngle = currentImbalance * maximumYawAngle
                             + irregularWobble * maximumWobbleYawAngle
                             + tremor * maximumTremorAngle * 0.55f
                             + outwardPulse * outwardLurchAngle * 0.45f;
            float lateralAmount = currentImbalance * maximumLateralOffset
                                  + irregularWobble * maximumWobbleOffset
                                  + tremor * maximumTremorOffset
                                  + outwardPulse * maximumWobbleOffset * 0.45f;

            Quaternion baseRotation = Quaternion.Euler(0f, 0f, followAngle);
            Quaternion imbalanceRotation = Quaternion.Euler(
                0f,
                yawAngle,
                rollAngle);
            Quaternion cameraRotation = baseRotation * imbalanceRotation;

            Vector3 lateralOffset = baseRotation
                                    * Vector3.right
                                    * lateralAmount;
            Vector3 cameraPosition = followPoint
                                     - cameraRotation * Vector3.forward
                                     * cameraDistance
                                     + lateralOffset;
            transform.SetPositionAndRotation(cameraPosition, cameraRotation);
        }

        private static bool PreviewKeyDown(KeyCode alphaKey, KeyCode keypadKey)
        {
            return Input.GetKeyDown(alphaKey) || Input.GetKeyDown(keypadKey);
        }

        private void OnValidate()
        {
            positionDamping = Mathf.Max(0f, positionDamping);
            rotationDamping = Mathf.Max(0f, rotationDamping);
            lightImbalance = Mathf.Clamp01(lightImbalance);
            mediumImbalance = Mathf.Clamp01(mediumImbalance);
            severeImbalance = Mathf.Clamp01(severeImbalance);
            maximumRollAngle = Mathf.Clamp(maximumRollAngle, 0f, 30f);
            maximumYawAngle = Mathf.Clamp(maximumYawAngle, 0f, 40f);
            maximumLateralOffset = Mathf.Max(0f, maximumLateralOffset);
            imbalanceSpringFrequency = Mathf.Clamp(
                imbalanceSpringFrequency,
                0.1f,
                5f);
            imbalanceDampingRatio = Mathf.Clamp(
                imbalanceDampingRatio,
                0.1f,
                1.5f);
            imbalanceNoiseAngle = Mathf.Clamp(imbalanceNoiseAngle, 0f, 4f);
            imbalanceNoiseFrequency = Mathf.Clamp(
                imbalanceNoiseFrequency,
                0.05f,
                3f);
            wobbleStartImbalance = Mathf.Clamp(wobbleStartImbalance, 0f, 0.95f);
            wobbleFrequency = Mathf.Clamp(wobbleFrequency, 0.1f, 4f);
            maximumWobbleRollAngle = Mathf.Clamp(
                maximumWobbleRollAngle,
                0f,
                15f);
            maximumWobbleYawAngle = Mathf.Clamp(
                maximumWobbleYawAngle,
                0f,
                15f);
            maximumWobbleOffset = Mathf.Max(0f, maximumWobbleOffset);
            tremorFrequency = Mathf.Clamp(tremorFrequency, 1f, 15f);
            maximumTremorAngle = Mathf.Clamp(maximumTremorAngle, 0f, 5f);
            maximumTremorOffset = Mathf.Max(0f, maximumTremorOffset);
            outwardLurchAngle = Mathf.Clamp(outwardLurchAngle, 0f, 10f);
        }
    }
}
