using System;
using UnityEngine;

namespace AnimalGame.MapTest
{
    /// <summary>
    /// Persistent authoring data for one fixed height-map level. Runtime systems
    /// continue to query MapTestSceneController, so assigning this asset changes
    /// the source of the map without changing traversal, scan, or tumble APIs.
    /// </summary>
    [CreateAssetMenu(
        fileName = "HeightMapLevel",
        menuName = "Animal Game/Height Map Level")]
    public sealed class HeightMapLevelAsset : ScriptableObject
    {
        [Header("Height Source")]
        [SerializeField] private Texture2D heightMap;
        [SerializeField, Min(1f)] private float mapWidthMeters = 250f;
        [SerializeField, Min(1f)] private float mapHeightMeters = 250f;
        [SerializeField] private float minimumHeightMeters;
        [SerializeField] private float maximumHeightMeters = 70f;

        [Header("Physical Height Field")]
        [SerializeField, Range(128, 2048)] private int bakedHeightResolution = 2048;
        [SerializeField] private bool normalizeSourceRange = true;
        [SerializeField, Min(0f)] private float surfaceSmoothingSigmaMeters = 0.75f;

        [Header("Map Presentation")]
        [SerializeField, Range(128, 8000)] private int previewResolution = 2160;
        [SerializeField, Min(1f)] private float contourIntervalMeters = 8f;
        [SerializeField, Min(1f)] private float pixelsPerUnit = 32f;
        [SerializeField] private Shader dynamicContourShader;
        [SerializeField, Range(0.1f, 10f)] private float minimumContourWidth = 0.7f;
        [SerializeField, Range(0.1f, 10f)] private float maximumContourWidth = 3.68f;
        [SerializeField, Range(0.1f, 0.7f)] private float maximumContourCoverage = 0.3f;
        [SerializeField, Range(0.1f, 1.5f)] private float contourEdgeSoftness = 0.4f;
        [SerializeField, Range(16, 128)] private int viewportHeightSamples = 64;

#if UNITY_EDITOR
        [Header("Single Terrain Surface Authoring")]
        [Tooltip("The one repeatable pattern used by the first terrain-surface prototype. Painting only controls where this pattern exists.")]
        [SerializeField] private Texture2D surfacePatternTexture;

        [Tooltip("Colour multiplied into the source pattern when the permanent surface visual is baked in the Editor.")]
        [SerializeField] private Color surfaceTint = Color.white;

        [Tooltip("Final opacity baked into painted terrain pixels.")]
        [SerializeField, Range(0f, 1f)] private float surfaceOpacity = 0.35f;

        [Tooltip("Logical map metres covered by one complete repetition of the source pattern.")]
        [SerializeField, Min(0.1f)] private float surfaceTileSizeMeters = 8f;

        [Tooltip("Resolution of the permanent RGBA visual generated by the Editor. Runtime only reads this finished texture.")]
        [SerializeField, Range(256, 4096)] private int surfaceBakeResolution = 2048;

        [Tooltip("Resolution of the persistent painted/not-painted authoring mask. This data is used by the Editor and is not sampled by the runtime map material.")]
        [SerializeField, Range(64, 1024)] private int surfaceMaskResolution = 512;

        [SerializeField, HideInInspector] private byte[] surfaceMask = Array.Empty<byte>();
#endif

        [Header("Baked Terrain Surface Runtime")]
        [Tooltip("Permanent Editor-baked terrain visual. The runtime never composes or modifies this texture.")]
        [SerializeField] private Texture2D bakedSurfaceVisual;

        [Tooltip("Softness of the screen-space UI reveal boundary in pixels. This affects only the circular display cutoff, not painted terrain boundaries.")]
        [SerializeField, Min(0f)] private float surfaceRevealEdgePixels = 4f;

        [SerializeField, HideInInspector] private int surfaceBakeRevision;

        [Header("Color Palette")]
        [SerializeField] private Color backgroundColor =
            new Color(0.008f, 0.012f, 0.017f, 1f);
        [SerializeField] private Color lowHeightColor = Color.black;
        [SerializeField] private Color middleHeightColor = Color.black;
        [SerializeField] private Color highHeightColor = Color.black;
        [SerializeField] private Color contourColor =
            new Color(0.92f, 0.97f, 1f, 1f);

        public Texture2D HeightMap => heightMap;
        public Vector2 MapSizeMeters => new Vector2(mapWidthMeters, mapHeightMeters);
        public float MinimumHeightMeters => minimumHeightMeters;
        public float MaximumHeightMeters => maximumHeightMeters;
        public int BakedHeightResolution => bakedHeightResolution;
        public bool NormalizeSourceRange => normalizeSourceRange;
        public float SurfaceSmoothingSigmaMeters => surfaceSmoothingSigmaMeters;
        public int PreviewResolution => previewResolution;
        public float ContourIntervalMeters => contourIntervalMeters;
        public float PixelsPerUnit => pixelsPerUnit;
        public Shader DynamicContourShader => dynamicContourShader;
        public float MinimumContourWidth => minimumContourWidth;
        public float MaximumContourWidth => maximumContourWidth;
        public float MaximumContourCoverage => maximumContourCoverage;
        public float ContourEdgeSoftness => contourEdgeSoftness;
        public int ViewportHeightSamples => viewportHeightSamples;
        public Texture2D BakedSurfaceVisual => bakedSurfaceVisual;
        public float SurfaceRevealEdgePixels => surfaceRevealEdgePixels;
        public int SurfacePresentationHash
        {
            get
            {
                unchecked
                {
                    int hash = bakedSurfaceVisual != null
                        ? bakedSurfaceVisual.GetInstanceID()
                        : 0;
                    hash = hash * 397 ^ surfaceRevealEdgePixels.GetHashCode();
                    hash = hash * 397 ^ surfaceBakeRevision;
                    return hash;
                }
            }
        }
        public Color BackgroundColor => backgroundColor;
        public Color LowHeightColor => lowHeightColor;
        public Color MiddleHeightColor => middleHeightColor;
        public Color HighHeightColor => highHeightColor;
        public Color ContourColor => contourColor;
        public bool IsValid => heightMap != null
                               && mapWidthMeters > 0f
                               && mapHeightMeters > 0f
                               && maximumHeightMeters > minimumHeightMeters;

        public int ConfigurationHash
        {
            get
            {
                unchecked
                {
                    int hash = heightMap != null ? heightMap.GetInstanceID() : 0;
                    hash = hash * 397 ^ mapWidthMeters.GetHashCode();
                    hash = hash * 397 ^ mapHeightMeters.GetHashCode();
                    hash = hash * 397 ^ minimumHeightMeters.GetHashCode();
                    hash = hash * 397 ^ maximumHeightMeters.GetHashCode();
                    hash = hash * 397 ^ bakedHeightResolution;
                    hash = hash * 397 ^ normalizeSourceRange.GetHashCode();
                    hash = hash * 397 ^ surfaceSmoothingSigmaMeters.GetHashCode();
                    hash = hash * 397 ^ previewResolution;
                    hash = hash * 397 ^ contourIntervalMeters.GetHashCode();
                    hash = hash * 397 ^ pixelsPerUnit.GetHashCode();
                    hash = hash * 397 ^ (dynamicContourShader != null
                        ? dynamicContourShader.GetInstanceID()
                        : 0);
                    hash = hash * 397 ^ minimumContourWidth.GetHashCode();
                    hash = hash * 397 ^ maximumContourWidth.GetHashCode();
                    hash = hash * 397 ^ maximumContourCoverage.GetHashCode();
                    hash = hash * 397 ^ contourEdgeSoftness.GetHashCode();
                    hash = hash * 397 ^ viewportHeightSamples;
                    hash = hash * 397 ^ backgroundColor.GetHashCode();
                    hash = hash * 397 ^ lowHeightColor.GetHashCode();
                    hash = hash * 397 ^ middleHeightColor.GetHashCode();
                    hash = hash * 397 ^ highHeightColor.GetHashCode();
                    hash = hash * 397 ^ contourColor.GetHashCode();
                    return hash;
                }
            }
        }

#if UNITY_EDITOR
        public Texture2D SurfacePatternTexture => surfacePatternTexture;
        public Color SurfaceTint => surfaceTint;
        public float SurfaceOpacity => surfaceOpacity;
        public float SurfaceTileSizeMeters => surfaceTileSizeMeters;
        public int SurfaceBakeResolution => surfaceBakeResolution;
        public int SurfaceMaskResolution => surfaceMaskResolution;

        public int CalculateSurfaceAuthoringHash()
        {
            unchecked
            {
                int hash = surfacePatternTexture != null
                    ? surfacePatternTexture.GetInstanceID()
                    : 0;
                hash = hash * 397 ^ surfaceTint.GetHashCode();
                hash = hash * 397 ^ surfaceOpacity.GetHashCode();
                hash = hash * 397 ^ surfaceTileSizeMeters.GetHashCode();
                hash = hash * 397 ^ surfaceBakeResolution;
                hash = hash * 397 ^ surfaceMaskResolution;
                if (surfaceMask != null)
                {
                    for (int index = 0; index < surfaceMask.Length; index++)
                        hash = hash * 31 ^ surfaceMask[index];
                }

                return hash;
            }
        }

        public byte[] GetOrCreateSurfaceMask()
        {
            int requestedResolution = Mathf.Clamp(surfaceMaskResolution, 64, 1024);
            int requestedLength = requestedResolution * requestedResolution;
            if (surfaceMask != null && surfaceMask.Length == requestedLength)
                return surfaceMask;

            byte[] previousMask = surfaceMask;
            surfaceMask = new byte[requestedLength];
            if (previousMask == null || previousMask.Length == 0)
                return surfaceMask;

            int previousResolution = Mathf.RoundToInt(
                Mathf.Sqrt(previousMask.Length));
            if (previousResolution * previousResolution != previousMask.Length)
                return surfaceMask;

            for (int y = 0; y < requestedResolution; y++)
            {
                int sourceY = Mathf.Clamp(
                    Mathf.FloorToInt(
                        (y + 0.5f) / requestedResolution * previousResolution),
                    0,
                    previousResolution - 1);
                for (int x = 0; x < requestedResolution; x++)
                {
                    int sourceX = Mathf.Clamp(
                        Mathf.FloorToInt(
                            (x + 0.5f) / requestedResolution * previousResolution),
                        0,
                        previousResolution - 1);
                    surfaceMask[y * requestedResolution + x] =
                        previousMask[sourceY * previousResolution + sourceX];
                }
            }

            return surfaceMask;
        }

        public bool PaintSurfaceMask(
            Vector2 mapPositionMeters,
            float brushRadiusMeters,
            bool erase)
        {
            byte[] mask = GetOrCreateSurfaceMask();
            int resolution = Mathf.Clamp(surfaceMaskResolution, 64, 1024);
            Vector2 mapSize = MapSizeMeters;
            float radius = Mathf.Max(0.01f, brushRadiusMeters);
            float radiusSquared = radius * radius;
            int minimumX = Mathf.Clamp(
                Mathf.FloorToInt(
                    (mapPositionMeters.x - radius) / mapSize.x * resolution),
                0,
                resolution - 1);
            int maximumX = Mathf.Clamp(
                Mathf.CeilToInt(
                    (mapPositionMeters.x + radius) / mapSize.x * resolution),
                0,
                resolution - 1);
            int minimumY = Mathf.Clamp(
                Mathf.FloorToInt(
                    (mapPositionMeters.y - radius) / mapSize.y * resolution),
                0,
                resolution - 1);
            int maximumY = Mathf.Clamp(
                Mathf.CeilToInt(
                    (mapPositionMeters.y + radius) / mapSize.y * resolution),
                0,
                resolution - 1);
            byte targetValue = erase ? (byte)0 : byte.MaxValue;
            bool changed = false;

            for (int y = minimumY; y <= maximumY; y++)
            {
                float pixelMapY = (y + 0.5f) / resolution * mapSize.y;
                for (int x = minimumX; x <= maximumX; x++)
                {
                    float pixelMapX = (x + 0.5f) / resolution * mapSize.x;
                    float deltaX = pixelMapX - mapPositionMeters.x;
                    float deltaY = pixelMapY - mapPositionMeters.y;
                    if (deltaX * deltaX + deltaY * deltaY > radiusSquared)
                        continue;

                    int index = y * resolution + x;
                    if (mask[index] == targetValue)
                        continue;

                    mask[index] = targetValue;
                    changed = true;
                }
            }

            return changed;
        }

        public bool FillSurfaceMask(bool painted)
        {
            byte[] mask = GetOrCreateSurfaceMask();
            byte targetValue = painted ? byte.MaxValue : (byte)0;
            bool changed = false;
            for (int index = 0; index < mask.Length; index++)
            {
                if (mask[index] == targetValue)
                    continue;

                mask[index] = targetValue;
                changed = true;
            }

            return changed;
        }

        public void SetBakedSurfaceVisual(Texture2D texture)
        {
            bakedSurfaceVisual = texture;
            unchecked
            {
                surfaceBakeRevision++;
            }
        }
#endif

        private void OnValidate()
        {
            mapWidthMeters = Mathf.Max(1f, mapWidthMeters);
            mapHeightMeters = Mathf.Max(1f, mapHeightMeters);
            maximumHeightMeters = Mathf.Max(
                minimumHeightMeters + 0.01f,
                maximumHeightMeters);
            bakedHeightResolution = Mathf.Clamp(bakedHeightResolution, 128, 2048);
            surfaceSmoothingSigmaMeters = Mathf.Max(0f, surfaceSmoothingSigmaMeters);
            previewResolution = Mathf.Clamp(previewResolution, 128, 8000);
            contourIntervalMeters = Mathf.Max(1f, contourIntervalMeters);
            pixelsPerUnit = Mathf.Max(1f, pixelsPerUnit);
            minimumContourWidth = Mathf.Clamp(minimumContourWidth, 0.1f, 10f);
            maximumContourWidth = Mathf.Clamp(maximumContourWidth, 0.1f, 10f);
            maximumContourCoverage = Mathf.Clamp(maximumContourCoverage, 0.1f, 0.7f);
            contourEdgeSoftness = Mathf.Clamp(contourEdgeSoftness, 0.1f, 1.5f);
            viewportHeightSamples = Mathf.Clamp(viewportHeightSamples, 16, 128);
            surfaceRevealEdgePixels = Mathf.Max(0f, surfaceRevealEdgePixels);
#if UNITY_EDITOR
            surfaceOpacity = Mathf.Clamp01(surfaceOpacity);
            surfaceTileSizeMeters = Mathf.Max(0.1f, surfaceTileSizeMeters);
            surfaceBakeResolution = Mathf.Clamp(surfaceBakeResolution, 256, 4096);
            surfaceMaskResolution = Mathf.Clamp(surfaceMaskResolution, 64, 1024);
#endif
        }
    }
}
